INHERIT: mkdoc_site/nav.yml

site_name: pyPaperFlow 文档
site_description: 面向科研工作者的自动化文献处理与知识发现平台
site_url: https://maybebio.github.io/pyPaperFlow/
repo_url: https://github.com/MaybeBio/pyPaperFlow
repo_name: MaybeBio/pyPaperFlow
docs_dir: mkdoc_site
edit_uri: edit/main/mkdoc_site/

theme:
  name: material
  language: zh
  features:
    - navigation.indexes
    - navigation.top
    - navigation.tracking
    - toc.integrate
    - search.suggest
    - search.highlight
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式

markdown_extensions:
  - admonition
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
